USE HEALTHCARE;

ALTER TABLE PATIENTS
ADD CONSTRAINT FK_DIAGNOSISID
FOREIGN KEY (DIAGNOSISID) REFERENCES DIAGNOSES(DIAGNOSISID);

ALTER TABLE PATIENTS
ADD CONSTRAINT FK_OUTCOMEID
FOREIGN KEY (OUTCOMEID) REFERENCES OUTCOMES(OUTCOMEID);

ALTER TABLE LABS
ADD CONSTRAINT FK_PATIENTID
FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(PATIENTID);

SELECT * FROM PATIENTS;
SELECT * FROM DIAGNOSES;